id: P1B1854EB
initial_creation_type: input
source_metadata:
  title: Religious History by Yar lung Jo bo
  author: ཡར་ལུང་ཇོ་བོ་ཤཱཀྱ་རིན་ཆེན།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2019-12-16);
    revision in process, thematic TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།; This text was initially OCR-processed by
    the Rime Centre Moscow. (src)
  - Text input:Rime Centre Moscow, OCR-processed
  - 'Editorial process: Mathias Fermer (mf), Kunga Dorje (kun)'
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:ངག་དབང་། ed. (ngag), Kunga Dorje (kun)
  text_witnesses: https://sakyaresearch.org/sources/339
  bases:
    c16b:
      title: Religious History by Yar lung Jo bo
      order: 1
      base_file: c16b.txt
created_at: '2022-04-15T19:11:26.129676'
last_modified_at: '2022-04-15T19:11:26.129684'
quality: null
